apiVersion: v1
kind: Service
metadata:
  name: ww-lb
spec:
  externalIPs:
  - 141.98.207.84
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31200
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ww
    type: webwork
  sessionAffinity: None
  type: LoadBalancer
